# TCL File Generated by Component Editor 18.1
# Fri Oct 04 03:20:10 JST 2019
# DO NOT MODIFY


# 
# led_matrix_ctl "led_matrix_ctl" v1.0
#  2019.10.04.03:20:10
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module led_matrix_ctl
# 
set_module_property DESCRIPTION ""
set_module_property NAME led_matrix_ctl
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR "Kent Nakajima"
set_module_property DISPLAY_NAME led_matrix_ctl
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE false
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL Controller_q_ip
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file controller.sv SYSTEM_VERILOG PATH src/controller.sv TOP_LEVEL_FILE
add_fileset_file driver.sv SYSTEM_VERILOG PATH src/driver.sv
add_fileset_file cascade_counter.sv SYSTEM_VERILOG PATH src/cascade_counter.sv
add_fileset_file line_buffer.sv SYSTEM_VERILOG PATH src/line_buffer.sv

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL Controller_q_ip
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file controller.sv SYSTEM_VERILOG PATH src/controller.sv TOP_LEVEL_FILE
add_fileset_file driver.sv SYSTEM_VERILOG PATH src/driver.sv
add_fileset_file cascade_counter.sv SYSTEM_VERILOG PATH src/cascade_counter.sv
add_fileset_file line_buffer.sv SYSTEM_VERILOG PATH src/line_buffer.sv

add_fileset SIM_VHDL SIM_VHDL "" ""
set_fileset_property SIM_VHDL TOP_LEVEL Controller_q_ip
set_fileset_property SIM_VHDL ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VHDL ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file controller.sv SYSTEM_VERILOG PATH src/controller.sv TOP_LEVEL_FILE
add_fileset_file driver.sv SYSTEM_VERILOG PATH src/driver.sv
add_fileset_file cascade_counter.sv SYSTEM_VERILOG PATH src/cascade_counter.sv
add_fileset_file line_buffer.sv SYSTEM_VERILOG PATH src/line_buffer.sv


# 
# parameters
# 


# 
# display items
# 


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset reset Input 1


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clock clk Input 1


# 
# connection point abcde
# 
add_interface abcde conduit end
set_interface_property abcde associatedClock clk
set_interface_property abcde associatedReset reset
set_interface_property abcde ENABLED true
set_interface_property abcde EXPORT_OF ""
set_interface_property abcde PORT_NAME_MAP ""
set_interface_property abcde CMSIS_SVD_VARIABLES ""
set_interface_property abcde SVD_ADDRESS_GROUP ""

add_interface_port abcde abcde abcde Output 5


# 
# connection point rgb_12
# 
add_interface rgb_12 conduit end
set_interface_property rgb_12 associatedClock clk
set_interface_property rgb_12 associatedReset reset
set_interface_property rgb_12 ENABLED true
set_interface_property rgb_12 EXPORT_OF ""
set_interface_property rgb_12 PORT_NAME_MAP ""
set_interface_property rgb_12 CMSIS_SVD_VARIABLES ""
set_interface_property rgb_12 SVD_ADDRESS_GROUP ""

add_interface_port rgb_12 r1 r1 Output 1
add_interface_port rgb_12 g1 g1 Output 1
add_interface_port rgb_12 b1 b1 Output 1
add_interface_port rgb_12 r2 r2 Output 1
add_interface_port rgb_12 b2 b2 Output 1
add_interface_port rgb_12 g2 g2 Output 1


# 
# connection point lat_oe
# 
add_interface lat_oe conduit end
set_interface_property lat_oe associatedClock clk
set_interface_property lat_oe associatedReset reset
set_interface_property lat_oe ENABLED true
set_interface_property lat_oe EXPORT_OF ""
set_interface_property lat_oe PORT_NAME_MAP ""
set_interface_property lat_oe CMSIS_SVD_VARIABLES ""
set_interface_property lat_oe SVD_ADDRESS_GROUP ""

add_interface_port lat_oe lat lat Output 1
add_interface_port lat_oe oe oe Output 1


# 
# connection point clk
# 
add_interface clk clock start
set_interface_property clk associatedDirectClock ""
set_interface_property clk clockRate 0
set_interface_property clk clockRateKnown false
set_interface_property clk ENABLED true
set_interface_property clk EXPORT_OF ""
set_interface_property clk PORT_NAME_MAP ""
set_interface_property clk CMSIS_SVD_VARIABLES ""
set_interface_property clk SVD_ADDRESS_GROUP ""

add_interface_port clk clk clk Output 1

